name: Deploy a S3

# El workflow se activa en cada push hacia la rama 'main'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Descarga el código de tu repositorio al runner
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2. Configura las credenciales de AWS usando los Secrets
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Sincroniza el contenido de tu repo al bucket S3
      # --delete: Elimina archivos en S3 que ya no están en tu repositorio
      # --exclude: Evita subir archivos innecesarios de Git
      - name: Desplegar archivos a S3
        run: aws s3 sync . s3://${{ secrets.S3_BUCKET }} --delete --exclude ".git/*" --exclude ".github/*"